// @ts-check
// ESLint for the Angular app (`npm run lint` → `ng lint`, AUD-335).
// Project rules from CLAUDE.md are errors; rules with many pre-existing hits
// sit at "warn" with an AUD-335 follow-up note instead of a repo-wide sweep
// (other audit plans edit the same files).
import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";
import angular from "angular-eslint";

export default defineConfig([
  {
    // Generated by `supabase gen types`; a hand fix would be overwritten.
    ignores: ["src/app/core/database.types.ts"],
  },
  {
    linterOptions: {
      reportUnusedDisableDirectives: "warn",
    },
  },
  {
    files: ["**/*.ts"],
    extends: [
      eslint.configs.recommended,
      tseslint.configs.recommended,
      tseslint.configs.stylistic,
      angular.configs.tsRecommended,
    ],
    processor: angular.processInlineTemplates,
    rules: {
      "@angular-eslint/directive-selector": [
        "error",
        {
          type: "attribute",
          prefix: "sc",
          style: "camelCase",
        },
      ],
      "@angular-eslint/component-selector": [
        "error",
        {
          type: "element",
          prefix: "sc",
          style: "kebab-case",
        },
      ],
      // CLAUDE.md: OnPush everywhere in production code.
      "@angular-eslint/prefer-on-push-component-change-detection": "error",
      // Not an error yet: neuro-field.directive.ts still has one @Input()
      // (AUD-229, block D17).
      "@angular-eslint/prefer-signals": "warn",
      // AUD-335 follow-up: pre-existing hits, not auto-fixable (2026-09-28).
      "@typescript-eslint/no-empty-function": "warn", // 27 hits
      "@typescript-eslint/no-unused-vars": "warn", // 16 hits
      "@typescript-eslint/no-explicit-any": "warn", // 12 hits
      "no-useless-escape": "warn", // 5 hits
      "no-useless-assignment": "warn", // 5 hits
      "@typescript-eslint/no-unused-expressions": "warn", // 4 hits
      "no-control-regex": "warn", // 2 hits
    },
  },
  {
    // Test-host components in specs and shared test helpers need no OnPush;
    // several audit plans add more of them (plans README §4a, D04 row).
    files: ["**/*.spec.ts", "src/app/testing/**/*.ts"],
    rules: {
      "@angular-eslint/prefer-on-push-component-change-detection": "off",
    },
  },
  {
    files: ["**/*.html"],
    extends: [
      angular.configs.templateRecommended,
      angular.configs.templateAccessibility,
    ],
    rules: {
      // AUD-335 follow-up: pre-existing hits, not auto-fixable (2026-09-28).
      "@angular-eslint/template/eqeqeq": "warn", // 81 hits
      "@angular-eslint/template/click-events-have-key-events": "warn", // 20 hits
      "@angular-eslint/template/interactive-supports-focus": "warn", // 19 hits
      "@angular-eslint/template/label-has-associated-control": "warn", // 2 hits
      "@angular-eslint/template/role-has-required-aria": "warn", // 1 hit
      "@angular-eslint/template/alt-text": "warn", // 1 hit
    },
  },
]);
