"""Tests against the synthetic P4K fixture (Phase 2 § F2 — Layer 1).

The fixture is generated by `scripts/build-synthetic-fixture.py` and
committed to the repo (4 KB, 100 % MIT-clean).
"""

from __future__ import annotations

import zipfile
from pathlib import Path

import pytest

from sc_extract.thresholds import aggregate_score, heuristic_check_entity

FIXTURE = Path(__file__).parent / "fixtures" / "synthetic.p4k"


@pytest.fixture(scope="module")
def fixture_path() -> Path:
    assert FIXTURE.exists(), (
        f"missing fixture at {FIXTURE} — "
        "run `python data-uploader/python/scripts/build-synthetic-fixture.py`"
    )
    return FIXTURE


def test_fixture_is_valid_zip(fixture_path: Path) -> None:
    with zipfile.ZipFile(fixture_path, "r") as zf:
        # Sentinel + 5 ships + 10 items + manifest = 17 entries
        names = zf.namelist()
        assert "Data/Game.dcb" in names
        ships = [n for n in names if n.startswith("Data/Objects/Spaceships/")]
        items = [n for n in names if n.startswith("Data/Items/")]
        assert len(ships) == 5
        assert len(items) == 10


def test_fixture_dcb_is_sentinel(fixture_path: Path) -> None:
    """Real DataCore is a CryEngine binary blob — synthetic ships a marker."""
    with zipfile.ZipFile(fixture_path, "r") as zf:
        with zf.open("Data/Game.dcb") as fp:
            data = fp.read()
    assert data.startswith(b"SC-COMPANION-SYNTHETIC-DCB"), (
        "fixture marker missing — was the fixture regenerated against the "
        "wrong build-synthetic-fixture.py?"
    )


def test_validator_scores_synthetic_below_real(fixture_path: Path) -> None:
    """The synthetic fixture is intentionally tiny — the Pure-Counter validator
    should flag it as critically low quality (well below any real extract)."""
    # Counts that would come from extracting the fixture
    counts = {"ships": 5, "items": 10, "weapons": 0, "components": 0, "strings": 0}
    score, warnings = aggregate_score(counts)
    assert score < 30, f"synthetic fixture scored too high ({score}) — thresholds too lenient?"
    # Every counter should produce a warning since none meet the warning floor
    assert len(warnings) >= 4


def test_heuristic_on_synthetic_ship() -> None:
    ship = {"name": "TEST_FixtureA_Scout", "mass": 12000, "hp_main_hull": 4500}
    assert heuristic_check_entity("ship", ship) == []


def test_heuristic_flags_missing_mass_on_synthetic() -> None:
    ship = {"name": "TEST_BrokenShip", "hp_main_hull": 1000}  # no mass
    warnings = heuristic_check_entity("ship", ship)
    assert any("mass" in w for w in warnings)
