// Real hardpoint anchors from the Data Uploader 0.48.0 silhouette build
// (LIVE 4.10.193.11644, H:\sc-out\643\out\silhouettes\rows) — only the
// fields the Holotable's leader layout needs: [portId, x %, y %].
// The Nomad keeps all 96 anchors (one per hardpoint node; 17 are pins, 16 of
// them match), the Javelin only the anchors of its pins (41 of 47 match; 213
// anchors in the row). Pin lists = the ports the Holotable pins for each ship
// (configurable blocks, display order), read off the Holodeck on 2026-10-08.
// Refs #642.
import type { HoloSilhouette, SilhouetteAnchor } from '../holo-silhouette';
import { ringPositions } from '../holo/codex-holo-model';

type AnchorTuple = readonly [portId: string, x: number, y: number];

export interface HoloAnchorFixture {
  className: string;
  /** The ports the table pins, in pin order (pin 1 first). */
  pins: readonly string[];
  silhouette: HoloSilhouette;
}

function silhouette(className: string, bbox: HoloSilhouette['bbox'], anchors: readonly AnchorTuple[]): HoloSilhouette {
  return {
    schema: 1,
    kind: 'ship',
    classNameSlug: className.toLowerCase(),
    build: { channel: 'LIVE', patchVersion: '4.10.0', buildNumber: '4.10.193.11644' },
    generatedAt: null,
    toolVersion: '0.48.0-dev',
    source: null,
    viewBox: '0 0 1000 1000',
    // The outline is irrelevant to the layout: the bbox as a rectangle.
    path: `M${bbox.x} ${bbox.y}h${bbox.w}v${bbox.h}h${-bbox.w}Z`,
    bbox,
    scaleMPerUnit: null,
    anchors: anchors.map(
      ([portId, x, y]): SilhouetteAnchor => ({ portId, x, y, side: null, depth: null, source: 'mesh', helper: portId, clamped: false }),
    ),
    unresolved: [],
  };
}

/** The fixture's pins as the stage places them: on the matching anchor
 * (case-folded port name), else on a ring hugging the outline's width — the
 * stage's fallback while anchored pins are on the table. */
export function leaderPins(fx: HoloAnchorFixture): { portName: string; index: number; x: number; y: number; resolved: boolean }[] {
  const byPort = new Map(fx.silhouette.anchors.map((a) => [a.portId.toLowerCase(), a]));
  const b = fx.silhouette.bbox;
  const ring = { cx: (b.x + b.w / 2) / 10, cy: 50, rx: b.w / 20 + 2, ry: 46 };
  const spots = ringPositions(ring, fx.pins.filter((p) => !byPort.has(p.toLowerCase())).length);
  let k = 0;
  return fx.pins.map((portName, i) => {
    const a = byPort.get(portName.toLowerCase());
    const pos = a ? { x: a.x, y: a.y } : spots[k++];
    return { portName, index: i + 1, x: pos.x, y: pos.y, resolved: !!a };
  });
}

export const NOMAD_ANCHORS: HoloAnchorFixture = {
  className: 'CNOU_Nomad',
  pins: [
    'hardpoint_weapon_top_left',
    'hardpoint_weapon_top_right',
    'hardpoint_weapon_bottom',
    'hardpoint_turret',
    'hardpoint_missiles_wing_left',
    'hardpoint_missiles_wing_right',
    'hardpoint_shield_generator_01',
    'hardpoint_shield_generator_02',
    'hardpoint_shield_generator_03',
    'hardpoint_power_plant',
    'hardpoint_quantum_drive',
    'hardpoint_radar',
    'hardpoint_cooler_left',
    'hardpoint_cooler_right',
    'hardpoint_lifesupport',
    'hardpoint_countermeasure_launcher_left',
    'hardpoint_countermeasure_launcher_right',
  ],
  silhouette: silhouette('CNOU_Nomad', { x: 137.21, y: 0, w: 725.59, h: 1000 }, [
    ['hardpoint_armor', 50, 58.2],
    ['hardpoint_avionics_1', 46.3, 43.6],
    ['hardpoint_avionics_2', 53.6, 43.6],
    ['hardpoint_batteries', 50, 48.5],
    ['hardpoint_bed', 42.3, 23.8],
    ['hardpoint_bench', 53.7, 28],
    ['hardpoint_cargo_bed', 50, 65.7],
    ['hardpoint_cockpit_door', 50, 15.9],
    ['hardpoint_cockpit_flair', 48.4, 2.4],
    ['hardpoint_cockpit_flair_hang', 51.1, 3.6],
    ['hardpoint_controller_capacitor_assignment', 50, 58.1],
    ['hardpoint_controller_comms', 50, 62.2],
    ['hardpoint_controller_cooler', 50, 62.2],
    ['hardpoint_controller_door', 50, 62.2],
    ['hardpoint_controller_energy', 50, 62.2],
    ['hardpoint_controller_flight', 50, 62.2],
    ['hardpoint_controller_light', 50, 62.2],
    ['hardpoint_controller_missile', 49.5, 2.7],
    ['hardpoint_controller_shield', 50, 62.2],
    ['hardpoint_controller_weapon', 50, 62.2],
    ['hardpoint_cooler_left', 50.3, 26.6],
    ['hardpoint_cooler_rack', 50, 26.5],
    ['hardpoint_cooler_right', 49.7, 26.6],
    ['hardpoint_countermeasure_launcher_left', 41.8, 55.4],
    ['hardpoint_countermeasure_launcher_right', 58.1, 55.4],
    ['hardpoint_dashboard_pilot', 50, 3.3],
    ['hardpoint_door_entrance', 28, 58.3],
    ['hardpoint_ext_lights', 50, 62.2],
    ['hardpoint_foyer_door', 50, 36],
    ['hardpoint_fuel_intake_left', 38.7, 8.9],
    ['hardpoint_fuel_intake_right', 61.3, 8.9],
    ['hardpoint_fuel_tank_left', 35, 31.3],
    ['hardpoint_fuel_tank_right', 65, 31.3],
    ['hardpoint_gravitry_generator', 50, 41.7],
    ['hardpoint_int_cockpit', 50, 10.7],
    ['hardpoint_int_foyer', 50, 44.4],
    ['hardpoint_int_foyer_hall', 36.1, 52.4],
    ['hardpoint_int_habitation', 50, 26.5],
    ['hardpoint_jump_drive', 50, 46.5],
    ['hardpoint_lg_front_left', 24.1, 33.9],
    ['hardpoint_lg_front_right', 75.8, 33.9],
    ['hardpoint_lg_left', 32.1, 32.4],
    ['hardpoint_lg_rear_left', 24.1, 35.5],
    ['hardpoint_lg_rear_right', 75.9, 35.5],
    ['hardpoint_lg_right', 67.9, 32.4],
    ['hardpoint_life_support', 50, 20],
    ['hardpoint_locker', 44.1, 40.2],
    ['hardpoint_locker_door', 44.1, 40.2],
    ['hardpoint_missiles_wing_left', 25.6, 22.4],
    ['hardpoint_missiles_wing_right', 74.4, 22.4],
    ['hardpoint_paint', 50, 62.2],
    ['hardpoint_ping', 50, 62.2],
    ['hardpoint_power_plant', 63.5, 52.1],
    ['hardpoint_power_plant_rack', 61.9, 50.9],
    ['hardpoint_quantum_drive', 64, 52.4],
    ['hardpoint_quantum_fuel_tank', 63, 52],
    ['hardpoint_radar', 50, 17.5],
    ['hardpoint_relay_cockpit', 50, 44.4],
    ['hardpoint_scanner', 50, 62.2],
    ['hardpoint_seat_access', 50, 6.9],
    ['hardpoint_seat_pilot', 50, 3.3],
    ['hardpoint_seataccess_sidedoor', 32, 55.2],
    ['hardpoint_self_destruct_pilot', 50, 62.2],
    ['hardpoint_shield_generator_01', 50, 20.3],
    ['hardpoint_shield_generator_02', 50, 21.3],
    ['hardpoint_shield_generator_03', 50, 22.3],
    ['hardpoint_shield_rack', 50, 21.3],
    ['hardpoint_table_counter', 59.1, 30],
    ['hardpoint_thruster_main_left', 36.1, 68.2],
    ['hardpoint_thruster_main_right', 63.8, 68.2],
    ['hardpoint_thruster_mav_left_front_bot', 31.1, 12.6],
    ['hardpoint_thruster_mav_left_front_top', 33.9, 14.3],
    ['hardpoint_thruster_mav_left_mid_bot', 19.4, 38.3],
    ['hardpoint_thruster_mav_left_mid_top', 20.2, 37.6],
    ['hardpoint_thruster_mav_left_rear_bot', 31, 72.2],
    ['hardpoint_thruster_mav_left_rear_top', 31.2, 71.9],
    ['hardpoint_thruster_mav_right_front_bot', 68.9, 12.6],
    ['hardpoint_thruster_mav_right_front_top', 66.1, 14.3],
    ['hardpoint_thruster_mav_right_mid_bot', 80.5, 38.3],
    ['hardpoint_thruster_mav_right_mid_top', 79.8, 37.6],
    ['hardpoint_thruster_mav_right_rear_bot', 68.9, 72.2],
    ['hardpoint_thruster_mav_right_rear_top', 68.8, 71.9],
    ['hardpoint_thruster_retro_left', 38.9, 10.1],
    ['hardpoint_thruster_retro_right', 61, 10.1],
    ['hardpoint_toilet', 55.9, 40.2],
    ['hardpoint_toilet_door', 60.7, 42],
    ['hardpoint_turret', 50, 87.8],
    ['hardpoint_vehicle_destroyed', 50, 49.3],
    ['hardpoint_weapon_bottom', 50, 7.2],
    ['hardpoint_weapon_rack_01', 34.5, 49.1],
    ['hardpoint_weapon_rack_02', 38.6, 55],
    ['hardpoint_weapon_regen_pool', 50, 59.4],
    ['hardpoint_weapon_regen_pool_turrets', 50, 59.4],
    ['hardpoint_weapon_top_left', 48.6, 56.5],
    ['hardpoint_weapon_top_right', 51.4, 56.5],
    ['landingpad_helper', 50, 44.4],
  ]),
};

export const JAVELIN_ANCHORS: HoloAnchorFixture = {
  className: 'AEGS_Javelin',
  pins: [
    'hardpoint_turret_front_left_upper',
    'hardpoint_turret_centre_left_upper',
    'hardpoint_turret_rear_left_upper',
    'hardpoint_turret_front_right_upper',
    'hardpoint_turret_centre_right_upper',
    'hardpoint_turret_rear_right_upper',
    'hardpoint_turret_nose_left_upper',
    'hardpoint_turret_nose_right_upper',
    'hardpoint_turret_nose_left_lower',
    'hardpoint_turret_nose_right_lower',
    'hardpoint_turret_front_lower',
    'hardpoint_turret_centre_lower',
    'hardpoint_turret_rear_lower',
    'hardpoint_turret_tail_upper',
    'hardpoint_turret_tail_lower',
    'hardpoint_torpedo_launcher_left',
    'hardpoint_torpedo_launcher_right',
    'hardpoint_missile_launcher_front_left',
    'hardpoint_missile_launcher_front_right',
    'hardpoint_missile_launcher_centre_left',
    'hardpoint_missile_launcher_centre_right',
    'hardpoint_missile_launcher_rear_left',
    'hardpoint_missile_launcher_rear_right',
    'hardpoint_shield_generator_01',
    'hardpoint_shield_generator_02',
    'hardpoint_shield_generator_03',
    'hardpoint_shield_generator_04',
    'hardpoint_powerplant_01',
    'hardpoint_powerplant_02',
    'hardpoint_powerplant_03',
    'hardpoint_powerplant_04',
    'hardpoint_quantum_drive',
    'hardpoint_cockpit_radar',
    'hardpoint_radar',
    'hardpoint_cooler_right_03',
    'hardpoint_cooler_right_04',
    'hardpoint_cooler_right_05',
    'hardpoint_cooler_right_06',
    'hardpoint_lifesupport',
    'hardpoint_countermeasures_left',
    'hardpoint_countermeasures_left_02',
    'hardpoint_countermeasures_left_03',
    'hardpoint_countermeasures_left_04',
    'hardpoint_countermeasures_right',
    'hardpoint_countermeasures_right_02',
    'hardpoint_countermeasures_right_03',
    'hardpoint_countermeasures_right_04',
  ],
  silhouette: silhouette('AEGS_Javelin', { x: 248.54, y: 0, w: 502.93, h: 1000 }, [
    ['hardpoint_cockpit_radar', 57, 61.7],
    ['hardpoint_cooler_right_03', 55.1, 62.7],
    ['hardpoint_cooler_right_04', 55.1, 62.7],
    ['hardpoint_cooler_right_05', 55.1, 62.7],
    ['hardpoint_cooler_right_06', 55.1, 62.7],
    ['hardpoint_countermeasures_left', 38.7, 51.9],
    ['hardpoint_countermeasures_left_02', 37.8, 22.4],
    ['hardpoint_countermeasures_left_03', 35.8, 79.7],
    ['hardpoint_countermeasures_left_04', 38.7, 47.9],
    ['hardpoint_countermeasures_right', 61.1, 51.9],
    ['hardpoint_countermeasures_right_02', 62, 22.4],
    ['hardpoint_countermeasures_right_03', 64, 79.7],
    ['hardpoint_countermeasures_right_04', 61.1, 47.9],
    ['hardpoint_lifesupport', 49.9, 53.9],
    ['hardpoint_powerplant_01', 49.9, 84.4],
    ['hardpoint_powerplant_02', 49.9, 84.4],
    ['hardpoint_powerplant_03', 49.9, 84.4],
    ['hardpoint_powerplant_04', 49.9, 84.4],
    ['hardpoint_quantum_drive', 49.8, 58.8],
    ['hardpoint_radar', 49.8, 62.7],
    ['hardpoint_shield_generator_01', 49.8, 64.6],
    ['hardpoint_shield_generator_02', 49.8, 64.6],
    ['hardpoint_shield_generator_03', 49.8, 64.6],
    ['hardpoint_shield_generator_04', 49.8, 64.6],
    ['hardpoint_torpedo_launcher_left', 46.8, 19.5],
    ['hardpoint_torpedo_launcher_right', 53, 19.5],
    ['hardpoint_turret_centre_left_upper', 40.3, 49.9],
    ['hardpoint_turret_centre_lower', 49.9, 57.7],
    ['hardpoint_turret_centre_right_upper', 59.5, 49.9],
    ['hardpoint_turret_front_left_upper', 40.3, 43.4],
    ['hardpoint_turret_front_lower', 49.9, 51.6],
    ['hardpoint_turret_front_right_upper', 59.5, 43.4],
    ['hardpoint_turret_nose_left_lower', 42.6, 32.7],
    ['hardpoint_turret_nose_left_upper', 42.6, 32.7],
    ['hardpoint_turret_nose_right_lower', 57.2, 32.8],
    ['hardpoint_turret_nose_right_upper', 57.2, 32.8],
    ['hardpoint_turret_rear_left_upper', 40.3, 56.4],
    ['hardpoint_turret_rear_lower', 49.9, 63.7],
    ['hardpoint_turret_rear_right_upper', 59.5, 56.4],
    ['hardpoint_turret_tail_lower', 49.9, 99.7],
    ['hardpoint_turret_tail_upper', 49.9, 99.7],
  ]),
};
