-- ============================================================
-- Ship skins (3D liveries) — catalog + public asset bucket
--
-- Backs the in-app skin selector: per ship, a list of paint liveries each with
-- an official name/description, a store-icon (WebP) and a web-ready textured
-- 3D model (glTF/glb, ~3 MB). Assets are produced by the data-uploader's
-- sc_extract.hull3d pipeline (100% from Data.p4k) and uploaded by a
-- service-role process.
--
-- Alpha-phase data policy: additive only — no existing table is touched.
-- ============================================================

-- ---- public asset bucket (glb models + webp icons) ----------------------
-- Public-read like codex-previews: 3D assets are non-sensitive game art derived
-- from the P4K. Writes are service-role only (no client write policy below).
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'ship-skins', 'ship-skins', true, 26214400,  -- 25 MB/object ceiling (glbs are ~3 MB)
  array['model/gltf-binary', 'image/webp', 'application/octet-stream']
)
on conflict (id) do nothing;

-- public read of ship-skins objects (anon + authenticated).
-- Idempotent: Postgres has no `create policy if not exists`, so drop first —
-- this migration must survive a re-run (db:push retries / db:reset).
drop policy if exists "ship_skins_public_read" on storage.objects;
create policy "ship_skins_public_read" on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'ship-skins');

-- ---- catalog table ------------------------------------------------------
create table if not exists public.ship_skins (
  id            uuid primary key default gen_random_uuid(),
  ship_id       text not null,              -- e.g. 'DRAK_Cutlass_Black' (codex_ships.class_name)
  skin_id       text not null,              -- slug, e.g. 'pirate'
  name          text not null,              -- official livery name (Localization)
  description   text not null default '',
  source        text not null default 'store',   -- store|event|subscriber|factory|pu_npc
  name_verified boolean not null default false,  -- name came straight from Localization
  model_path    text,                       -- ship-skins object path to the .glb (null = no 3D)
  icon_path     text,                       -- ship-skins object path to the .webp icon
  model_bytes   integer,
  sort          integer not null default 100,
  created_at    timestamptz not null default now(),
  constraint ship_skins_natkey unique (ship_id, skin_id)
);

create index if not exists ship_skins_ship_idx on public.ship_skins (ship_id, sort);

comment on table public.ship_skins is
  '3D paint liveries per ship. Assets in the public ship-skins bucket. '
  'Generated by data-uploader sc_extract.hull3d from Data.p4k. Service-role write only.';

-- ---- RLS: viewer-readable, service-role-writable (mirrors codex_*) -------
alter table public.ship_skins enable row level security;

drop policy if exists "ship_skins_authenticated_read" on public.ship_skins;
create policy "ship_skins_authenticated_read" on public.ship_skins
  for select to authenticated using (true);

-- No client write policy ⇒ writes denied; service_role bypasses RLS for ingest.
revoke insert, update, delete, truncate on public.ship_skins from authenticated, anon;
