// AUTO-GENERATED by `supabase gen types typescript` (via Supabase MCP).
// Project hcnqhvzlavdycidqyaai. Do not edit by hand — regenerate after migrations:
//   mcp generate_typescript_types  → save here.
// Hand-written Codex domain interfaces live in src/app/codex/codex.types.ts.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      api_request_log: {
        Row: {
          endpoint: string
          status: number
          token_hash: string
          ts: string
        }
        Insert: {
          endpoint: string
          status: number
          token_hash: string
          ts?: string
        }
        Update: {
          endpoint?: string
          status?: number
          token_hash?: string
          ts?: string
        }
        Relationships: []
      }
      api_tokens: {
        Row: {
          created_at: string
          id: string
          last_used_at: string | null
          name: string
          owner_user_id: string
          prefix: string
          revoked_at: string | null
          scopes: string[]
          token_hash: string
        }
        Insert: {
          created_at?: string
          id?: string
          last_used_at?: string | null
          name: string
          owner_user_id: string
          prefix: string
          revoked_at?: string | null
          scopes?: string[]
          token_hash: string
        }
        Update: {
          created_at?: string
          id?: string
          last_used_at?: string | null
          name?: string
          owner_user_id?: string
          prefix?: string
          revoked_at?: string | null
          scopes?: string[]
          token_hash?: string
        }
        Relationships: []
      }
      codex_ammunition: {
        Row: {
          build_id: string
          build_number: string
          channel: string
          class_name: string
          created_at: string
          guid: string | null
          id: string
          lifetime: number | null
          name_localized: string | null
          patch_version: string
          payload: Json
          size: number | null
          speed: number | null
        }
        Insert: {
          build_id: string
          build_number?: string
          channel: string
          class_name: string
          created_at?: string
          guid?: string | null
          id?: string
          lifetime?: number | null
          name_localized?: string | null
          patch_version: string
          payload: Json
          size?: number | null
          speed?: number | null
        }
        Update: {
          build_id?: string
          build_number?: string
          channel?: string
          class_name?: string
          created_at?: string
          guid?: string | null
          id?: string
          lifetime?: number | null
          name_localized?: string | null
          patch_version?: string
          payload?: Json
          size?: number | null
          speed?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "codex_ammunition_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_builds: {
        Row: {
          build_number: string
          channel: string
          created_at: string
          entity_counts: Json
          extracted_at: string | null
          id: string
          is_current: boolean
          manifest: Json
          patch_version: string
          quality_score: number | null
          schema_version: number
          tool_version: string | null
        }
        Insert: {
          build_number?: string
          channel: string
          created_at?: string
          entity_counts?: Json
          extracted_at?: string | null
          id?: string
          is_current?: boolean
          manifest?: Json
          patch_version: string
          quality_score?: number | null
          schema_version?: number
          tool_version?: string | null
        }
        Update: {
          build_number?: string
          channel?: string
          created_at?: string
          entity_counts?: Json
          extracted_at?: string | null
          id?: string
          is_current?: boolean
          manifest?: Json
          patch_version?: string
          quality_score?: number | null
          schema_version?: number
          tool_version?: string | null
        }
        Relationships: []
      }
      codex_components: {
        Row: {
          attach_type: string | null
          build_id: string
          build_number: string
          channel: string
          class_name: string
          created_at: string
          entity_kind: string
          grade: string | null
          guid: string | null
          id: string
          is_variant: boolean
          kind: string | null
          manufacturer_code: string | null
          name_localized: string | null
          patch_version: string
          payload: Json
          size: number | null
          sub_type: string | null
        }
        Insert: {
          attach_type?: string | null
          build_id: string
          build_number?: string
          channel: string
          class_name: string
          created_at?: string
          entity_kind?: string
          grade?: string | null
          guid?: string | null
          id?: string
          is_variant?: boolean
          kind?: string | null
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version: string
          payload: Json
          size?: number | null
          sub_type?: string | null
        }
        Update: {
          attach_type?: string | null
          build_id?: string
          build_number?: string
          channel?: string
          class_name?: string
          created_at?: string
          entity_kind?: string
          grade?: string | null
          guid?: string | null
          id?: string
          is_variant?: boolean
          kind?: string | null
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version?: string
          payload?: Json
          size?: number | null
          sub_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "codex_components_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_entity_strings: {
        Row: {
          build_id: string
          build_number: string
          channel: string
          created_at: string
          entity_class_name: string
          entity_kind: string
          field: string
          id: string
          lang: string
          loc_key: string | null
          patch_version: string
          value: string | null
        }
        Insert: {
          build_id: string
          build_number?: string
          channel: string
          created_at?: string
          entity_class_name: string
          entity_kind: string
          field: string
          id?: string
          lang: string
          loc_key?: string | null
          patch_version: string
          value?: string | null
        }
        Update: {
          build_id?: string
          build_number?: string
          channel?: string
          created_at?: string
          entity_class_name?: string
          entity_kind?: string
          field?: string
          id?: string
          lang?: string
          loc_key?: string | null
          patch_version?: string
          value?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "codex_entity_strings_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_item_ports: {
        Row: {
          build_id: string
          build_number: string
          channel: string
          created_at: string
          flags: string[]
          id: string
          max_size: number | null
          min_size: number | null
          parent_class_name: string
          parent_kind: string
          patch_version: string
          port_index: number
          port_name: string | null
          types: string[]
        }
        Insert: {
          build_id: string
          build_number?: string
          channel: string
          created_at?: string
          flags?: string[]
          id?: string
          max_size?: number | null
          min_size?: number | null
          parent_class_name: string
          parent_kind: string
          patch_version: string
          port_index?: number
          port_name?: string | null
          types?: string[]
        }
        Update: {
          build_id?: string
          build_number?: string
          channel?: string
          created_at?: string
          flags?: string[]
          id?: string
          max_size?: number | null
          min_size?: number | null
          parent_class_name?: string
          parent_kind?: string
          patch_version?: string
          port_index?: number
          port_name?: string | null
          types?: string[]
        }
        Relationships: [
          {
            foreignKeyName: "codex_item_ports_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_items: {
        Row: {
          attach_type: string | null
          build_id: string
          build_number: string
          channel: string
          class_name: string
          created_at: string
          entity_kind: string
          grade: string | null
          guid: string | null
          id: string
          is_variant: boolean
          manufacturer_code: string | null
          name_localized: string | null
          patch_version: string
          payload: Json
          size: number | null
          sub_type: string | null
        }
        Insert: {
          attach_type?: string | null
          build_id: string
          build_number?: string
          channel: string
          class_name: string
          created_at?: string
          entity_kind?: string
          grade?: string | null
          guid?: string | null
          id?: string
          is_variant?: boolean
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version: string
          payload: Json
          size?: number | null
          sub_type?: string | null
        }
        Update: {
          attach_type?: string | null
          build_id?: string
          build_number?: string
          channel?: string
          class_name?: string
          created_at?: string
          entity_kind?: string
          grade?: string | null
          guid?: string | null
          id?: string
          is_variant?: boolean
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version?: string
          payload?: Json
          size?: number | null
          sub_type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "codex_items_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_manufacturers: {
        Row: {
          build_id: string
          build_number: string
          channel: string
          class_name: string
          created_at: string
          guid: string | null
          id: string
          manufacturer_code: string | null
          name_localized: string | null
          patch_version: string
          payload: Json
        }
        Insert: {
          build_id: string
          build_number?: string
          channel: string
          class_name: string
          created_at?: string
          guid?: string | null
          id?: string
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version: string
          payload: Json
        }
        Update: {
          build_id?: string
          build_number?: string
          channel?: string
          class_name?: string
          created_at?: string
          guid?: string | null
          id?: string
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version?: string
          payload?: Json
        }
        Relationships: [
          {
            foreignKeyName: "codex_manufacturers_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_seed_tokens: {
        Row: {
          created_at: string
          disabled: boolean
          expires_at: string | null
          label: string | null
          token: string
        }
        Insert: {
          created_at?: string
          disabled?: boolean
          expires_at?: string | null
          label?: string | null
          token: string
        }
        Update: {
          created_at?: string
          disabled?: boolean
          expires_at?: string | null
          label?: string | null
          token?: string
        }
        Relationships: []
      }
      codex_ships: {
        Row: {
          build_id: string
          build_number: string
          channel: string
          class_name: string
          created_at: string
          crew_size: number | null
          entity_kind: string
          guid: string | null
          id: string
          is_variant: boolean
          manufacturer_code: string | null
          name_localized: string | null
          patch_version: string
          payload: Json
          role: string | null
        }
        Insert: {
          build_id: string
          build_number?: string
          channel: string
          class_name: string
          created_at?: string
          crew_size?: number | null
          entity_kind?: string
          guid?: string | null
          id?: string
          is_variant?: boolean
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version: string
          payload: Json
          role?: string | null
        }
        Update: {
          build_id?: string
          build_number?: string
          channel?: string
          class_name?: string
          created_at?: string
          crew_size?: number | null
          entity_kind?: string
          guid?: string | null
          id?: string
          is_variant?: boolean
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version?: string
          payload?: Json
          role?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "codex_ships_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      codex_weapons: {
        Row: {
          build_id: string
          build_number: string
          channel: string
          class_name: string
          created_at: string
          entity_kind: string
          grade: string | null
          guid: string | null
          id: string
          is_variant: boolean
          manufacturer_code: string | null
          name_localized: string | null
          patch_version: string
          payload: Json
          size: number | null
          sub_type: string | null
          weapon_class: string | null
        }
        Insert: {
          build_id: string
          build_number?: string
          channel: string
          class_name: string
          created_at?: string
          entity_kind?: string
          grade?: string | null
          guid?: string | null
          id?: string
          is_variant?: boolean
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version: string
          payload: Json
          size?: number | null
          sub_type?: string | null
          weapon_class?: string | null
        }
        Update: {
          build_id?: string
          build_number?: string
          channel?: string
          class_name?: string
          created_at?: string
          entity_kind?: string
          grade?: string | null
          guid?: string | null
          id?: string
          is_variant?: boolean
          manufacturer_code?: string | null
          name_localized?: string | null
          patch_version?: string
          payload?: Json
          size?: number | null
          sub_type?: string | null
          weapon_class?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "codex_weapons_build_id_fkey"
            columns: ["build_id"]
            isOneToOne: false
            referencedRelation: "codex_builds"
            referencedColumns: ["id"]
          },
        ]
      }
      desktop_releases: {
        Row: {
          created_at: string
          id: string
          is_current: boolean
          notes: string | null
          platforms: Json
          release_token: string
          version: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_current?: boolean
          notes?: string | null
          platforms?: Json
          release_token?: string
          version: string
        }
        Update: {
          created_at?: string
          id?: string
          is_current?: boolean
          notes?: string | null
          platforms?: Json
          release_token?: string
          version?: string
        }
        Relationships: []
      }
      news_cache: {
        Row: {
          external_id: string
          fetched_at: string
          published_at: string
          source: string
          thumbnail: string | null
          title: string
          url: string
        }
        Insert: {
          external_id: string
          fetched_at?: string
          published_at: string
          source: string
          thumbnail?: string | null
          title: string
          url: string
        }
        Update: {
          external_id?: string
          fetched_at?: string
          published_at?: string
          source?: string
          thumbnail?: string | null
          title?: string
          url?: string
        }
        Relationships: []
      }
      p4k_bundles: {
        Row: {
          build_number: string
          channel: Database["public"]["Enums"]["p4k_channel"]
          created_at: string
          data_url: string | null
          diff_summary: Json | null
          disabled: boolean
          disabled_at: string | null
          disabled_by: string | null
          disabled_reason: string | null
          entity_counts: Json
          id: string
          manifest: Json
          patch_version: string
          quality_score: number | null
          schema_version: number
          tool_version: string | null
          uploaded_by: string
        }
        Insert: {
          build_number?: string
          channel: Database["public"]["Enums"]["p4k_channel"]
          created_at?: string
          data_url?: string | null
          diff_summary?: Json | null
          disabled?: boolean
          disabled_at?: string | null
          disabled_by?: string | null
          disabled_reason?: string | null
          entity_counts?: Json
          id?: string
          manifest: Json
          patch_version: string
          quality_score?: number | null
          schema_version?: number
          tool_version?: string | null
          uploaded_by: string
        }
        Update: {
          build_number?: string
          channel?: Database["public"]["Enums"]["p4k_channel"]
          created_at?: string
          data_url?: string | null
          diff_summary?: Json | null
          disabled?: boolean
          disabled_at?: string | null
          disabled_by?: string | null
          disabled_reason?: string | null
          entity_counts?: Json
          id?: string
          manifest?: Json
          patch_version?: string
          quality_score?: number | null
          schema_version?: number
          tool_version?: string | null
          uploaded_by?: string
        }
        Relationships: []
      }
      p4k_uploads: {
        Row: {
          detected_channel: Database["public"]["Enums"]["p4k_channel"]
          detected_version: string | null
          error: string | null
          id: string
          original_name: string
          processed_at: string | null
          result: Json | null
          size_bytes: number
          status: Database["public"]["Enums"]["p4k_status"]
          storage_path: string
          uploaded_at: string
          user_id: string
        }
        Insert: {
          detected_channel?: Database["public"]["Enums"]["p4k_channel"]
          detected_version?: string | null
          error?: string | null
          id?: string
          original_name: string
          processed_at?: string | null
          result?: Json | null
          size_bytes: number
          status?: Database["public"]["Enums"]["p4k_status"]
          storage_path: string
          uploaded_at?: string
          user_id: string
        }
        Update: {
          detected_channel?: Database["public"]["Enums"]["p4k_channel"]
          detected_version?: string | null
          error?: string | null
          id?: string
          original_name?: string
          processed_at?: string | null
          result?: Json | null
          size_bytes?: number
          status?: Database["public"]["Enums"]["p4k_status"]
          storage_path?: string
          uploaded_at?: string
          user_id?: string
        }
        Relationships: []
      }
      patch_versions: {
        Row: {
          channel: string
          detected_at: string
          version: string
        }
        Insert: {
          channel: string
          detected_at?: string
          version: string
        }
        Update: {
          channel?: string
          detected_at?: string
          version?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string | null
          id: string
          is_approved: boolean
          preferred_channel: string | null
          role: string
          rsi_handle: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string | null
          id: string
          is_approved?: boolean
          preferred_channel?: string | null
          role?: string
          rsi_handle?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string | null
          id?: string
          is_approved?: boolean
          preferred_channel?: string | null
          role?: string
          rsi_handle?: string | null
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      p4k_bundles_public_stats: {
        Row: {
          best_quality_score: number | null
          bundle_count: number | null
          channel: Database["public"]["Enums"]["p4k_channel"] | null
          latest_at: string | null
          patch_version: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      current_user_role: { Args: never; Returns: string }
      diff_bundle: { Args: { new_id: string; prev_id: string }; Returns: Json }
      ingest_bundle_atomic: {
        Args: {
          p_build_number: string
          p_channel: Database["public"]["Enums"]["p4k_channel"]
          p_entity_counts: Json
          p_manifest: Json
          p_patch_version: string
          p_quality_score: number
          p_schema_version: number
          p_tool_version: string
          p_uploader: string
        }
        Returns: {
          bundle_id: string
          diff_summary: Json
          prev_bundle_id: string
        }[]
      }
      is_admin:
        | { Args: never; Returns: boolean }
        | { Args: { uid: string }; Returns: boolean }
      is_collaborator: { Args: never; Returns: boolean }
      list_p4k_bundles_for_collaborator:
        | {
            Args: never
            Returns: {
              channel: Database["public"]["Enums"]["p4k_channel"]
              created_at: string
              entity_counts: Json
              id: string
              patch_version: string
              quality_score: number
              schema_version: number
              tool_version: string
              uploaded_by_email: string
              uploaded_by_id: string
              uploaded_by_name: string
            }[]
          }
        | {
            Args: { include_disabled?: boolean; include_history?: boolean }
            Returns: {
              build_number: string
              channel: Database["public"]["Enums"]["p4k_channel"]
              created_at: string
              diff_summary: Json
              disabled: boolean
              disabled_reason: string
              entity_counts: Json
              id: string
              patch_version: string
              quality_score: number
              schema_version: number
              tool_version: string
              uploaded_by_email: string
              uploaded_by_id: string
              uploaded_by_name: string
            }[]
          }
      list_users_for_admin: {
        Args: never
        Returns: {
          created_at: string
          display_name: string
          email: string
          id: string
          last_sign_in_at: string
          role: string
        }[]
      }
      set_bundle_disabled: {
        Args: { bundle_id: string; new_disabled: boolean; reason?: string }
        Returns: undefined
      }
      set_current_codex_build: {
        Args: { p_build_id: string }
        Returns: undefined
      }
      set_user_role: {
        Args: { new_role: string; target_id: string }
        Returns: undefined
      }
    }
    Enums: {
      p4k_channel: "live" | "ptu" | "eptu" | "tech-preview" | "unknown"
      p4k_status: "pending" | "processing" | "done" | "failed"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      p4k_channel: ["live", "ptu", "eptu", "tech-preview", "unknown"],
      p4k_status: ["pending", "processing", "done", "failed"],
    },
  },
} as const
