"""Build a 100 % MIT-clean synthetic P4K fixture for CI + tests.

Phase 2 § F2 (Test-Fixture-Strategie):
  • Layer 1: tiny synthetic P4K — what THIS script produces.
    100 % own IP, free to commit, runs in GitHub Actions Linux runners.
  • Layer 2: 50-100 MB subset of a real Data.p4k (see build-subset-fixture.py)
    — NOT committed, devs run locally only.

The synthetic fixture is a regular ZIP file with the .p4k extension. It contains
a sentinel Data/Game.dcb (not a real DataCore — just a marker so future tests
can assert "the extractor recognised this is a P4K-shaped archive") plus a
handful of structured Data/Objects/Spaceships/<ship>.xml and Data/Items/<item>.xml
files.

The schema mirrors what we expect real SC content to look like, but the field
values are entirely fabricated. No CIG assets included.

Usage:
    python data-uploader/python/scripts/build-synthetic-fixture.py \\
        --out data-uploader/python/tests/fixtures/synthetic.p4k

The fixture is committed via the test directory so CI has it offline.
"""

from __future__ import annotations

import argparse
import json
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape

# Fabricated ship + item names — patterned after SC conventions but
# NOT actual CIG IP. Manufacturer prefixes are also made up.
SYNTHETIC_SHIPS = [
    {"name": "TEST_FixtureA_Scout", "mass": 12000, "hp_main_hull": 4500},
    {"name": "TEST_FixtureB_Freighter", "mass": 86000, "hp_main_hull": 26000},
    {"name": "TEST_FixtureC_Interceptor", "mass": 8500, "hp_main_hull": 3200},
    {"name": "TEST_FixtureD_Carrier", "mass": 210000, "hp_main_hull": 72000},
    {"name": "TEST_FixtureE_Industrial", "mass": 145000, "hp_main_hull": 48000},
]

SYNTHETIC_ITEMS = [
    {"name": "TEST_Shield_T1_Mock", "category": "shield", "size": 1},
    {"name": "TEST_Shield_T2_Mock", "category": "shield", "size": 2},
    {"name": "TEST_PowerPlant_T1_Mock", "category": "power", "size": 1},
    {"name": "TEST_PowerPlant_T2_Mock", "category": "power", "size": 2},
    {"name": "TEST_Cooler_T1_Mock", "category": "cooler", "size": 1},
    {"name": "TEST_QDrive_T1_Mock", "category": "qdrive", "size": 1},
    {"name": "TEST_QDrive_T2_Mock", "category": "qdrive", "size": 2},
    {"name": "TEST_Weapon_S1_Mock", "category": "weapon", "size": 1},
    {"name": "TEST_Weapon_S2_Mock", "category": "weapon", "size": 2},
    {"name": "TEST_Weapon_S3_Mock", "category": "weapon", "size": 3},
]


def ship_xml(ship: dict) -> str:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<Spaceship name="{escape(ship["name"])}"\n'
        f'           mass="{ship["mass"]}"\n'
        f'           hp_main_hull="{ship["hp_main_hull"]}" />\n'
    )


def item_xml(item: dict) -> str:
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<Item name="{escape(item["name"])}"\n'
        f'      category="{item["category"]}"\n'
        f'      size="{item["size"]}" />\n'
    )


def manifest_dict() -> dict:
    return {
        "synthetic": True,
        "ip_clean": True,
        "ships": [s["name"] for s in SYNTHETIC_SHIPS],
        "items": [i["name"] for i in SYNTHETIC_ITEMS],
        "note": "Generated by build-synthetic-fixture.py — no CIG content.",
    }


def build(out_path: Path) -> None:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out_path, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        # Sentinel marker — real Data.p4k contains Data/Game.dcb (DataCore
        # binary). Real parsing happens in real fixtures; here we just place
        # a non-empty placeholder so an existence check passes.
        zf.writestr(
            "Data/Game.dcb",
            b"SC-COMPANION-SYNTHETIC-DCB\x00" + b"\x00" * 32,
        )
        for ship in SYNTHETIC_SHIPS:
            zf.writestr(
                f"Data/Objects/Spaceships/{ship['name']}.xml",
                ship_xml(ship),
            )
        for item in SYNTHETIC_ITEMS:
            zf.writestr(f"Data/Items/{item['name']}.xml", item_xml(item))
        zf.writestr(
            "MANIFEST_synthetic.json",
            json.dumps(manifest_dict(), indent=2),
        )

    size_kb = out_path.stat().st_size / 1024
    print(f"[fixture] wrote {out_path} ({size_kb:.1f} KB)")
    print(f"[fixture] ships: {len(SYNTHETIC_SHIPS)}  items: {len(SYNTHETIC_ITEMS)}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build synthetic P4K fixture (MIT-clean)")
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("data-uploader/python/tests/fixtures/synthetic.p4k"),
    )
    args = parser.parse_args()
    build(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
